CREATE TABLE SavedJobs (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  jobseekerId BIGINT,
  jobId BIGINT,
  created_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6),
  updated_at DATETIME(6) DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  FOREIGN KEY (jobseekerId) REFERENCES users(id),
  FOREIGN KEY (jobId) REFERENCES jobs(id)
);