CREATE TABLE Analytics (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  totalJobsPosted INT DEFAULT 0,
  totalApplicationsReceived INT DEFAULT 0,
  totalHired INT DEFAULT 0,
  userId INT,
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (userId) REFERENCES User(id)
);